export const COUNTRIES_FR = [
  'Afghanistan',
  'Afrique Centrale',
  'Afrique du sud',
  'Albanie',
  'Algerie',
  'Allemagne',
  'Andorre',
  'Angola',
  'Anguilla',
  'Arabie Saoudite',
  'Argentine',
  'Armenie',
  'Australie',
  'Autriche',
  'Azerbaidjan',
  'Bahamas',
  'Bangladesh',
  'Barbade',
  'Bahrein',
  'Belgique',
  'Belize',
  'Benin',
  'Bermudes',
  'Bielorussie',
  'Bolivie',
  'Botswana',
  'Bhoutan',
  'Boznie Herzegovine',
  'Bresil',
  'Brunei',
  'Bulgarie',
  'Burkina Faso',
  'Burundi',
  'Caiman',
  'Cambodge',
  'Cameroun',
  'Canada',
  'Canaries',
  'Cap vert',
  'Chili',
  'Chine',
  'Chypre',
  'Colombie',
  'Comores',
  'Congo',
  'Congo democratique',
  'Cook',
  'Coree du Nord',
  'Coree du Sud',
  'Costa Rica',
  'Cote d Ivoire',
  'Croatie',
  'Cuba',
  'Danemark',
  'Djibouti',
  'Dominique',
  'Egypte',
  'Emirats Arabes Unis',
  'Equateur',
  'Erythree',
  'Espagne',
  'Estonie',
  'Etats Unis',
  'Ethiopie',
  'Falkland',
  'Feroe',
  'Fidji',
  'Finlande',
  'France',
  'Gabon',
  'Gambie',
  'Georgie',
  'Ghana',
  'Gibraltar',
  'Grece',
  'Grenade',
  'Groenland',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernesey',
  'Guinee',
  'Guinee Bissau',
  'Guinee',
  'Guyana',
  'Guyane Francaise',
  'Haiti',
  'Hawaii',
  'Honduras',
  'Hong Kong',
  'Hongrie',
  'Inde',
  'Indonesie',
  'Iran',
  'Iraq',
  'Irlande',
  'Islande',
  'Israel',
  'Italie',
  'Jamaique',
  'Jan',
  'Japon',
  'Jersey',
  'Jordanie',
  'Kazakhstan',
  'Kenya',
  'Kirghizstan',
  'Kiribati',
  'Koweit',
  'Laos',
  'Lesotho',
  'Lettonie',
  'Liban',
  'Liberia',
  'Liechtenstein',
  'Lituanie',
  'Luxembourg',
  'Lybie',
  'Macao',
  'Macedoine',
  'Madagascar',
  'Madère',
  'Malaisie',
  'Malawi',
  'Maldives',
  'Mali',
  'Malte',
  'Man',
  'Mariannes',
  'Maroc',
  'Marshall',
  'Martinique',
  'Maurice',
  'Mauritanie',
  'Mayotte',
  'Mexique',
  'Micronesie',
  'Midway',
  'Moldavie',
  'Monaco',
  'Mongolie',
  'Montserrat',
  'Mozambique',
  'Namibie',
  'Nauru',
  'Nepal',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk',
  'Norvege',
  'Nouvelle Caledonie',
  'Nouvelle Zelande',
  'Oman',
  'Ouganda',
  'Ouzbekistan',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papouasie Nouvelle Guinee',
  'Paraguay',
  'Pays Bas',
  'Perou',
  'Philippines',
  'Pologne',
  'Polynesie',
  'Porto Rico',
  'Portugal',
  'Qatar',
  'Republique Dominicaine',
  'Republique Tcheque',
  'Reunion',
  'Roumanie',
  'Royaume Uni',
  'Russie',
  'Rwanda',
  'Sahara',
  'Sainte Lucie',
  'Saint Marin',
  'Salomon',
  'Salvador',
  'Samoa Occidentales',
  'Samoa Americaine',
  'Sao Tome et Principe',
  'Senegal',
  'Seychelles',
  'Sierra',
  'Singapour',
  'Slovaquie',
  'Slovenie',
  'Somalie',
  'Soudan',
  'Sri Lanka',
  'Suede',
  'Suisse',
  'Surinam',
  'Swaziland',
  'Syrie',
  'Tadjikistan',
  'Taiwan',
  'Tonga',
  'Tanzanie',
  'Tchad',
  'Thailande',
  'Tibet',
  'Timor Oriental',
  'Togo',
  'Trinite et Tobago',
  'Tristan',
  'Tunisie',
  'Turkmenistan',
  'Turquie',
  'Ukraine',
  'Uruguay',
  'Vanuatu',
  'Vatican',
  'Venezuela',
  'Vierges Americaines',
  'Vierges Britanniques',
  'Vietnam',
  'Wake',
  'Wallis',
  'Yemen',
  'Yougoslavie',
  'Zambie',
  'Zimbabwe'
];
